/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkplus;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author pchin
 */
public class CargaArchivo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CargaArchivo.class.getName());
    private File archivoSeleccionado;
    private File rutaSeleccionada;

    /**
     * Creates new form CargaArchivo
     */
    public CargaArchivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboArchivo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboImpExp = new javax.swing.JComboBox<>();
        txtPath = new javax.swing.JTextField();
        btnPath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Archivo que desea importar/exportar: ");

        comboArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumnos", "Historico", "Lugares Carros", "Lugares Catedraticos", "Lugares Motos", "Registro Vehiculos" }));
        comboArchivo.setEnabled(false);
        comboArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboArchivoActionPerformed(evt);
            }
        });

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("¿Que desea hacer?");

        comboImpExp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Importar", "Exportar" }));
        comboImpExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboImpExpActionPerformed(evt);
            }
        });

        txtPath.setEditable(false);
        txtPath.setBackground(new java.awt.Color(255, 255, 255));
        txtPath.setText("Ruta de Archivo");

        btnPath.setText("...");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboImpExp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(comboArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboImpExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPath))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Connection con = ConexionSQL.conectar();
    String seleccion = comboImpExp.getSelectedItem().toString().toUpperCase();
    String seleccionA = comboArchivo.getSelectedItem().toString().toUpperCase();

    switch (seleccion) {

        case "IMPORTAR":
            switch (seleccionA) {
                case "ALUMNOS":
                    importarAlumnos(archivoSeleccionado, con);
                    break;
                case "LUGARES CARROS":
                    importarLugaresCarros(archivoSeleccionado, con);
                    break;
                case "LUGARES CATEDRATICOS":
                    importarLugaresCatedraticos(archivoSeleccionado, con);
                    break;
                case "LUGARES MOTOS":
                    importarLugaresMotos(archivoSeleccionado, con);
                    break;
                case "REGISTRO VEHICULOS":
                    importarRegistros(archivoSeleccionado, con);
                    break;
                case "HISTORICO":
                    JOptionPane.showMessageDialog(null, "No puedes importar registro histórico.");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Selección no válida.");
            }
            break;

        case "EXPORTAR":
            switch (seleccionA) {
                case "ALUMNOS":
                    exportarAlumnos(rutaSeleccionada, con);
                    break;
                case "LUGARES CARROS":
                    exportarLugaresCarros(rutaSeleccionada, con);
                    break;
                case "LUGARES CATEDRATICOS":
                    exportarLugaresCatedraticos(rutaSeleccionada, con);
                    break;
                case "LUGARES MOTOS":
                    exportarLugaresMotos(rutaSeleccionada, con);
                    break;
                case "REGISTRO VEHICULOS":
                    exportarRegistros(rutaSeleccionada, con);
                    break;
                case "HISTORICO":
                    exportarRegistros(rutaSeleccionada, con);  
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Selección no válida.");
            }
            break;

        default:
            JOptionPane.showMessageDialog(null, "Por favor selecciona una opción válida.");
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboImpExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboImpExpActionPerformed
        
        switch(comboImpExp.getSelectedItem().toString().toUpperCase()){
            
            case "IMPORTAR": 
                comboArchivo.setEnabled(true);
                comboArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumnos", "Lugares Carros", "Lugares Catedraticos", "Lugares Motos", "Registros"}));
            case "EXPORTAR":
                comboArchivo.setEnabled(true);
                comboArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumnos", "Historico", "Lugares Carros", "Lugares Catedraticos", "Lugares Motos", "Registros"}));
                txtPath.setText("Ruta donde deseas guardar tu archivo");
        }
        
    }//GEN-LAST:event_comboImpExpActionPerformed

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        String verificacionImpExp = comboImpExp.getSelectedItem().toString().toUpperCase();
        if(comboImpExp.getSelectedIndex() == -1 || comboArchivo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Porfavor Completa las Selecciones de arriba para continuar!!");
            return;
        }
        
        else{
            if(verificacionImpExp.equals("EXPORTAR")){
                JFileChooser chooser = new JFileChooser();
                chooser.setDialogTitle("Escoge la Ruta para guardar tu archivo");
                chooser.setSelectedFile(new File("Export.csv")); // nombre por defecto
                int seleccion = chooser.showSaveDialog(this);

                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    rutaSeleccionada = chooser.getSelectedFile();
                    txtPath.setText(rutaSeleccionada.getAbsolutePath());
                    System.out.println("Su ruta es: " + rutaSeleccionada.getAbsolutePath());
                } 
                else {
                    JOptionPane.showMessageDialog(this, "Seleccion de Ruta Invalida.");
                }
            }
            else{
                archivoSeleccionado = seleccionarCSV();
                txtPath.setText(archivoSeleccionado.getAbsolutePath());
            }
        }
            
        
        
        
    }//GEN-LAST:event_btnPathActionPerformed

    private void comboArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CargaArchivo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPath;
    private javax.swing.JComboBox<String> comboArchivo;
    private javax.swing.JComboBox<String> comboImpExp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
    
    public static File seleccionarCSV() {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Selecciona el archivo CSV a importar");
            int resultado = chooser.showOpenDialog(null);

            if (resultado == JFileChooser.APPROVE_OPTION) {
                return chooser.getSelectedFile();
            } else {
                System.out.println("No se seleccionó ningún archivo.");
                return null;
            }
        }
   
    
    public static void importarRegistros(File archivo, Connection con) {
            if (archivo == null) {
                System.out.println("⚠ No se seleccionó archivo.");
                return;
            }

            String linea;
            String separador = ","; // ESTE ES EL SEPARADOR DE COLUMNAS

            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                // Saltar la primera línea (cabecera)
                br.readLine();

                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(separador);

                    String placa = datos[0].trim();
                    String tipo = datos[1].trim();
                    String horaEntrada = datos[2].trim();
                    String horaSalida = datos[3].trim();

                    String sql = "INSERT INTO REGISTROS (placa, tipo, horaEntrada, horaSalida) VALUES (?, ?, ?, ?)";

                    try (PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setString(1, placa);
                        ps.setString(2, tipo);
                        ps.setString(3, horaEntrada);
                        ps.setString(4, horaSalida);
                        ps.executeUpdate();
                    }
                }

                System.out.println("✅ Datos importados correctamente desde el CSV.");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    public static void importarAlumnos(File archivo, Connection con) {
            if (archivo == null) {
                System.out.println("⚠ No se seleccionó archivo.");
                return;
            }

            String linea;
            String separador = ","; // ESTE ES EL SEPARADOR DE COLUMNAS

            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                // Saltar la primera línea (cabecera)
                br.readLine();

                while ((linea = br.readLine()) != null) {
                    String[] datos = linea.split(separador);

                    String carnet = datos[0].trim();
                    String nombres = datos[1].trim();
                    String apellidos = datos[2].trim();
                    String telefono = datos[3].trim();
                    String correo = datos[4].trim();
                    String placa = datos[5].trim();

                    String sql = "INSERT INTO Alumnos (carnet, nombres, apellidos, telefono, correo, placa) VALUES (?, ?, ?, ?, ?, ?)";

                    try (PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setString(1, carnet);
                        ps.setString(2, nombres);
                        ps.setString(3, apellidos);
                        ps.setString(4, telefono);
                        ps.setString(5, correo);
                        ps.setString(6, placa);
                        ps.executeUpdate();
                    }
                }

                System.out.println("✅ Datos importados correctamente desde el CSV.");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    public static void importarLugaresCarros(File archivo, Connection con) {
            if (archivo == null) {
                System.out.println("⚠ No se seleccionó archivo.");
                return;
            }

            String linea;
            String separador = ","; // ESTE ES EL SEPARADOR DE COLUMNAS

            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                // Saltar la primera línea (cabecera)
                br.readLine();

                while ((linea = br.readLine()) != null) {
                    
                    String[] datos = linea.split(separador);
                    String numero = datos[0].trim();
                    String ocupado = datos[1].trim();
                    
                    
                    
                    String sql = "INSERT INTO lugaresCarros (numero, ocupado, placa, hora_entrada) VALUES (?, ?, NULL, NULL)";

                    try (PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setString(1, numero);
                        ps.setString(2, ocupado);
                        ps.executeUpdate();
                    }
                }

                System.out.println("✅ Datos importados correctamente desde el CSV.");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    public static void importarLugaresCatedraticos(File archivo, Connection con) {
            if (archivo == null) {
                System.out.println("⚠ No se seleccionó archivo.");
                return;
            }

            String linea;
            String separador = ","; // ESTE ES EL SEPARADOR DE COLUMNAS

            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                // Saltar la primera línea (cabecera)
                br.readLine();

                while ((linea = br.readLine()) != null) {
                    
                    String[] datos = linea.split(separador);
                    String numero = datos[0].trim();
                    String ocupado = datos[1].trim();
                    
                    
                    
                    String sql = "INSERT INTO lugaresCatedraticos (numero, ocupado, placa, hora_entrada, tipoVehiculo) VALUES (?, ?, NULL, NULL, NULL)";

                    try (PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setString(1, numero);
                        ps.setString(2, ocupado);
                        ps.executeUpdate();
                    }
                }

                System.out.println("✅ Datos importados correctamente desde el CSV.");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    public static void importarLugaresMotos(File archivo, Connection con) {
            if (archivo == null) {
                System.out.println("⚠ No se seleccionó archivo.");
                return;
            }

            String linea;
            String separador = ","; // ESTE ES EL SEPARADOR DE COLUMNAS

            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                // Saltar la primera línea (cabecera)
                br.readLine();

                while ((linea = br.readLine()) != null) {
                    
                    String[] datos = linea.split(separador);
                    String numero = datos[0].trim();
                    String ocupado = datos[1].trim();
                    
                    
                    
                    String sql = "INSERT INTO lugaresMotos (numero, ocupado, placa, hora_entrada, tipoVehiculo) VALUES (?, ?, NULL, NULL)";

                    try (PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setString(1, numero);
                        ps.setString(2, ocupado);
                        ps.executeUpdate();
                    }
                }

                System.out.println("✅ Datos importados correctamente desde el CSV.");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    
    public static void exportarHistorico(File archivo, Connection con) {
            if (archivo == null) {
            System.out.println("No se seleccionó archivo.");
            return;
        }

        String sql = "SELECT idTicket, nombre, placa, hora_entrada, hora_salida, tipoVehiculo, esCatedratico, lugarOcupado, tarifa FROM historico";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             FileWriter fw = new FileWriter(archivo)) {

          
            fw.append("idTicket,nombre,placa,hora_entrada,hora_salida,tipoVehiculo,esCatedratico,lugarOcupado,tarifa\n");

    
            while (rs.next()) {
                
                // Control de valores nulos
                fw.append(rs.getString("idTicket") == null ? "" : rs.getString("idTicket")).append(",");
                fw.append(rs.getString("nombre") == null ? "" : rs.getString("nombre")).append(",");
                fw.append(rs.getString("placa") == null ? "" : rs.getString("placa")).append(",");
                fw.append(rs.getString("hora_entrada") == null ? "" : rs.getString("hora_entrada")).append(",");
                fw.append(rs.getString("hora_salida") == null ? "" : rs.getString("hora_salida")).append(",");
                fw.append(rs.getString("tipoVehiculo") == null ? "" : rs.getString("tipoVehiculo")).append(",");
                fw.append(rs.getString("esCatedratico") == null ? "" : rs.getString("esCatedratico")).append(",");
                fw.append(rs.getString("lugarOcupado") == null ? "" : rs.getString("lugarOcupado")).append(",");
                fw.append(rs.getString("tarifa") == null ? "" : rs.getString("tarifa")).append(",");
                
            }

            System.out.println("Archivo CSV generado correctamente en: " + archivo.getAbsolutePath());

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }
    public static void exportarRegistros(File archivo, Connection con) {
            if (archivo == null) {
            System.out.println("No se seleccionó archivo.");
            return;
        }

        String sql = "SELECT nombre, apellido, carnet, correo, telefono, placa, tipoVehiculo, esCatedratico FROM REGISTROS";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             FileWriter fw = new FileWriter(archivo)) {

          
            fw.append("nombre,apellido,carnet,correo,telefono,placa,tipoVehiculo,esCatedratico\n");

    
            while (rs.next()) {
                
                // Control de valores nulos
                fw.append(rs.getString("carnet") == null ? "" : rs.getString("carnet")).append(",");
                fw.append(rs.getString("nombres") == null ? "" : rs.getString("nombres")).append(",");
                fw.append(rs.getString("apellidos") == null ? "" : rs.getString("apellidos")).append(",");
                fw.append(rs.getString("telefono") == null ? "" : rs.getString("telefono")).append(",");
                fw.append(rs.getString("correo") == null ? "" : rs.getString("correo")).append(",");
                fw.append(rs.getString("placa") == null ? "" : rs.getString("placa")).append(",");
                
            }

            System.out.println("Archivo CSV generado correctamente en: " + archivo.getAbsolutePath());

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }
    public static void exportarAlumnos(File archivo, Connection con) {
            if (archivo == null) {
            System.out.println("No se seleccionó archivo.");
            return;
        }

        String sql = "SELECT carnet, nombres, apellidos, telefono, correo, placa FROM Alumnos";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             FileWriter fw = new FileWriter(archivo)) {

          
            fw.append("carnet,nombres,apellidos,telefono,correo,placa\n");

    
            while (rs.next()) {
                /*fw.append(rs.getString("carnet")).append(",");
                fw.append(rs.getString("nombres")).append(",");
                fw.append(rs.getString("apellidos")).append(",");
                fw.append(rs.getString("telefono")).append(",");
                fw.append(rs.getString("correo")).append(",");
                fw.append(rs.getString("placa")).append(",");*/
                
                // Control de valores nulos
                fw.append(rs.getString("carnet") == null ? "" : rs.getString("carnet")).append(",");
                fw.append(rs.getString("nombres") == null ? "" : rs.getString("nombres")).append(",");
                fw.append(rs.getString("apellidos") == null ? "" : rs.getString("apellidos")).append(",");
                fw.append(rs.getString("telefono") == null ? "" : rs.getString("telefono")).append(",");
                fw.append(rs.getString("correo") == null ? "" : rs.getString("correo")).append(",");
                fw.append(rs.getString("placa") == null ? "" : rs.getString("placa")).append(",");
                
            }

            System.out.println("Archivo CSV generado correctamente en: " + archivo.getAbsolutePath());

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }
    public static void exportarLugaresCarros(File archivo, Connection con) {
            if (archivo == null) {
            System.out.println("No se seleccionó archivo.");
            return;
        }

        String sql = "SELECT numero, ocupado, placa, hora_entrada FROM lugaresCarros";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             FileWriter fw = new FileWriter(archivo)) {

          
            fw.append("numero,ocupado,placa,hora_entrada\n");

    
            while (rs.next()) {
                fw.append(rs.getString("numero")).append(",");
                fw.append(rs.getString("ocupado")).append(",");
                
                // Control de valores nulos
                fw.append(rs.getString("placa") == null ? "" : rs.getString("placa")).append(",");
                fw.append(rs.getString("hora_entrada") == null ? "" : rs.getString("hora_entrada")).append(",");
                
            }

            System.out.println("Archivo CSV generado correctamente en: " + archivo.getAbsolutePath());

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }
    public static void exportarLugaresCatedraticos(File archivo, Connection con) {
            if (archivo == null) {
            System.out.println("No se selecciono archivo.");
            return;
        }

        String sql = "SELECT numero, ocupado, placa, hora_entrada, tipoVehiculo FROM lugaresCatedraticos";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             FileWriter fw = new FileWriter(archivo)) {

           
            fw.append("numero,ocupado,placa,hora_entrada,tipoVehiculo\n");

     
            while (rs.next()) {
                fw.append(rs.getString("numero")).append(",");
                fw.append(rs.getString("ocupado")).append(",");
                
                // Control de valores nulos
                fw.append(rs.getString("placa") == null ? "" : rs.getString("placa")).append(",");
                fw.append(rs.getString("hora_entrada") == null ? "" : rs.getString("hora_entrada")).append(",");
                fw.append(rs.getString("tipoVehiculo") == null ? "" : rs.getString("tipoVehiculo")).append("\n");
            }

            System.out.println("Archivo CSV generado correctamente en: " + archivo.getAbsolutePath());

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }
    public static void exportarLugaresMotos(File archivo, Connection con) {
            if (archivo == null) {
            System.out.println("No se seleccionó archivo.");
            return;
        }

        String sql = "SELECT numero, ocupado, placa, hora_entrada FROM lugaresMotos";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql);
             FileWriter fw = new FileWriter(archivo)) {

          
            fw.append("numero,ocupado,placa,hora_entrada\n");

    
            while (rs.next()) {
                fw.append(rs.getString("numero")).append(",");
                fw.append(rs.getString("ocupado")).append(",");
                
                // Control de valores nulos
                fw.append(rs.getString("placa") == null ? "" : rs.getString("placa")).append(",");
                fw.append(rs.getString("hora_entrada") == null ? "" : rs.getString("hora_entrada")).append(",");
                
            }

            System.out.println("Archivo CSV generado correctamente en: " + archivo.getAbsolutePath());

        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }
        }



