/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkplus;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author pchin
 */
public class NuevoTicket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoTicket.class.getName());

    /**
     * Creates new form NuevoTicket
     */
    public NuevoTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        radioCatedratico = new javax.swing.JRadioButton();
        btnFlat = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtCapacidad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 204, 224));

        labelPlaca.setFont(new java.awt.Font("Gontserrat SemiBold", 0, 24)); // NOI18N
        labelPlaca.setText("Placa");

        txtPlaca.setToolTipText("Ingresa el Numero de Placa");
        txtPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Gontserrat Medium", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gontserrat Medium", 0, 18)); // NOI18N
        jLabel2.setText("Carnet");

        txtCarnet.setEditable(false);
        txtCarnet.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Fecha y Hora");

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setText(fechaHoraFormateada);

        buttonGroup1.add(radioCatedratico);
        radioCatedratico.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        radioCatedratico.setText("Catedrático");
        radioCatedratico.setEnabled(false);

        buttonGroup2.add(btnFlat);
        btnFlat.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        btnFlat.setText("Flat (Q10.00)");

        jLabel4.setFont(new java.awt.Font("Gontserrat", 0, 14)); // NOI18N
        jLabel4.setText("Tarifa");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        jRadioButton1.setText("Variable Q2.00/ Hora (0-59min)");

        txtCapacidad.setFont(new java.awt.Font("Gontserrat", 0, 18)); // NOI18N
        txtCapacidad.setText("jLabel5");

        jButton1.setFont(new java.awt.Font("Gontserrat", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Carro" }));
        comboTipo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(labelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlaca)
                                    .addComponent(txtNombre)
                                    .addComponent(txtCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioCatedratico, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFlat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioCatedratico)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFlat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
   if(buttonGroup2.getSelection() == null ){

    JOptionPane.showMessageDialog(this, "Debes seleccionar al menos una tarifa ");
    
}    
else{
    
    String placa = txtPlaca.getText().trim();
    
    if (placa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa una placa");
        return;
    }    
    Connection con = ConexionSQL.conectar();
    
    String sql = "SELECT * FROM REGISTROS WHERE placa = ?";
    
    try (PreparedStatement ps = con.prepareStatement(sql)) {
        
        ps.setString(1, placa);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            
            String nombre = rs.getString("nombre");
            String carnet = rs.getString("carnet");
            String tipoV = rs.getString("tipovehiculo");
            
            Integer catedratico = rs.getInt("esCatedratico");
            
            txtNombre.setText(nombre);
            txtCarnet.setText(carnet);
            
            if(tipoV.equalsIgnoreCase("Carro")){
                comboTipo.setSelectedIndex(1);
            }    
            else if(tipoV.equalsIgnoreCase("Motocicleta")){
                comboTipo.setSelectedIndex(2);
            }           
            if (catedratico == 1){ radioCatedratico.setSelected(true);} 
            else { radioCatedratico.setSelected(false);}
            
            int opcion = JOptionPane.showConfirmDialog(this, "¿Desea Generar este Ticket?");
            if(opcion == JOptionPane.YES_OPTION){
                Integer lugarAsignado = 0;
                String tarifa = "";
                long totalPagar;
                Vehiculo vehTicket = new Vehiculo(placa, carnet, nombre, tipoV);
                LocalDateTime ahora = LocalDateTime.now();
                DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                String fechaHoraFormateada = ahora.format(formato);     
                if(btnFlat.isSelected()) //VERIFICACION PARA TARIFA PLANA
                { 
                    tarifa = "Flat";
                    totalPagar = 10;
                    if(tipoV.equalsIgnoreCase("Carro"))
                    {
                    if(radioCatedratico.isSelected()){ //SI ES CATEDRATICO REGISTRA UN CARRO EN UN LUGAR DE CATEDRATICO
                        
                    LugarDAO vehiculoAsignar = new LugarDAO(placa);
                    lugarAsignado = vehiculoAsignar.registrarEntradaCatedratico(placa, tipoV);
                    String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                    PreparedStatement ps2 = con.prepareStatement(sql2);
                    ps2.setString(1, placa);
                    ResultSet rs2 = ps2.executeQuery();
                    Integer idTicket = 0;
                    if (rs2.next()) {
                        idTicket = rs2.getInt("id");
                    }
                    Ticket ticketFlat = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                    ticketFlat.setIdTicket(idTicket);
                    ticketFlat.imprimirTicketFlatCatedratico();
                    rs2.close();
                    ps2.close();
                    }    
                    
                    else{ //Y SINO, REGISTRA UN CARRO EN UN LUGAR COMUN
                        
                    LugarDAO vehiculoAsignar = new LugarDAO(placa);
                    lugarAsignado = vehiculoAsignar.registrarEntradaCarro(placa);
                    String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                    PreparedStatement ps2 = con.prepareStatement(sql2);
                    ps2.setString(1, placa);
                    ResultSet rs2 = ps2.executeQuery();
                    Integer idTicket = 0;
                    if (rs2.next()) {
                        idTicket = rs2.getInt("id");
                        System.out.println("ID ENCONTRADO");
                    }
                    Ticket ticketFlat = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                    ticketFlat.setIdTicket(idTicket);
                    ticketFlat.imprimirTicketFlatCarro();
                    rs2.close();
                    ps2.close();
                    }                  
                    
                    }
                    else if(tipoV.equalsIgnoreCase("Moto")) //SI ES MOTO
                    {
                    if(radioCatedratico.isSelected()){ //SI ES CATEDRATICO REGISTRA UN MOTO EN UN LUGAR DE CATEDRATICO
                        
                    LugarDAO vehiculoAsignar = new LugarDAO(placa);
                    lugarAsignado = vehiculoAsignar.registrarEntradaCatedratico(placa, tipoV);
                    String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                    PreparedStatement ps2 = con.prepareStatement(sql2);
                    ps2.setString(1, placa);
                    ResultSet rs2 = ps2.executeQuery();
                    Integer idTicket = 0;
                    if (rs2.next()) {
                        idTicket = rs2.getInt("id");
                    }
                    Ticket ticketFlat = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                    ticketFlat.setIdTicket(idTicket);
                    ticketFlat.imprimirTicketFlatCatedratico();
                    rs2.close();
                    ps2.close();
                    }    
                    
                    else{ //Y SINO, REGISTRA UN MOTO EN UN LUGAR COMUN
                        
                    LugarDAO vehiculoAsignar = new LugarDAO(placa);
                    lugarAsignado = vehiculoAsignar.registrarEntradaMoto(placa);
                    String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                    PreparedStatement ps2 = con.prepareStatement(sql2);
                    ps2.setString(1, placa);
                    ResultSet rs2 = ps2.executeQuery();
                    Integer idTicket = 0;
                    if (rs2.next()) {
                        idTicket = rs2.getInt("id");
                    }
                    Ticket ticketFlat = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                    ticketFlat.setIdTicket(idTicket);
                    ticketFlat.imprimirTicketFlatMoto();
                    rs2.close();
                    ps2.close();
                    } 
                }
            }
                else{ //SI ES TARIFA VARIABLE
                    
                    tarifa = "Variable";
                    totalPagar = 0;
                    
                    if(tipoV.equalsIgnoreCase("Carro")) //SI ES CARRO
                    {
                        
                        if(radioCatedratico.isSelected()){ //SI ES CATEDRATICO REGISTRA UN CARRO EN UN LUGAR DE CATEDRATICO

                        LugarDAO vehiculoAsignar = new LugarDAO(placa);
                        lugarAsignado = vehiculoAsignar.registrarEntradaCatedratico(placa, tipoV);
                        String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                        PreparedStatement ps2 = con.prepareStatement(sql2);
                        ps2.setString(1, placa);
                        ResultSet rs2 = ps2.executeQuery();
                        Integer idTicket = 0;
                        if (rs2.next()) {
                        idTicket = rs2.getInt("id");
                        }
                        Ticket ticketVariable = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                        ticketVariable.setIdTicket(idTicket);
                        ticketVariable.imprimirTicketVariableCatedratico();
                        rs2.close();
                        ps2.close();
                        }    
                    
                        else{ //Y SINO, REGISTRA UN CARRO EN UN LUGAR COMUN

                        LugarDAO vehiculoAsignar = new LugarDAO(placa);
                        lugarAsignado = vehiculoAsignar.registrarEntradaCarro(placa);
                        String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                        PreparedStatement ps2 = con.prepareStatement(sql2);
                        ps2.setString(1, placa);
                        ResultSet rs2 = ps2.executeQuery();
                        Integer idTicket = 0;
                        if (rs2.next()) {
                            idTicket = rs2.getInt("id");
                        }
                        Ticket ticketVariable = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                        ticketVariable.setIdTicket(idTicket);
                        ticketVariable.imprimirTicketVariableCarro();
                        rs2.close();
                        ps2.close();
                        }                    
                    }
                    
                    else if(tipoV.equalsIgnoreCase("Moto")) //SI ES MOTO
                    {
                        
                        if(radioCatedratico.isSelected()){ //SI ES CATEDRATICO REGISTRA UNA MOTO EN UN LUGAR DE CATEDRATICO
                        
                            LugarDAO vehiculoAsignar = new LugarDAO(placa);
                            lugarAsignado = vehiculoAsignar.registrarEntradaCatedratico(placa, tipoV);
                            String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                            PreparedStatement ps2 = con.prepareStatement(sql2);
                            ps2.setString(1, placa);
                            ResultSet rs2 = ps2.executeQuery();
                            Integer idTicket = 0;
                            if (rs2.next()) {
                                idTicket = rs2.getInt("id");
                            }
                            Ticket ticketVariable = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                            ticketVariable.setIdTicket(idTicket);
                            ticketVariable.imprimirTicketVariableCatedratico();
                            rs2.close();
                            ps2.close();
                        }    
                        
                        else{ //Y SINO, REGISTRA UNA MOTO EN UN LUGAR DE MOTO
                            LugarDAO vehiculoAsignar = new LugarDAO(placa);
                            lugarAsignado = vehiculoAsignar.registrarEntradaMoto(placa);
                            String sql2 = "SELECT TOP 1 id FROM historico WHERE placa = ? ORDER BY id DESC";
                            PreparedStatement ps2 = con.prepareStatement(sql2);
                            ps2.setString(1, placa);
                            ResultSet rs2 = ps2.executeQuery();
                            Integer idTicket = 0;
                            if (rs2.next()) {
                                idTicket = rs2.getInt("id");
                            }
                            Ticket ticketVariable = new Ticket(vehTicket, tarifa, fechaHoraFormateada, tipoV, lugarAsignado, idTicket, totalPagar);
                            ticketVariable.setIdTicket(idTicket);
                            ticketVariable.imprimirTicketVariableMoto();
                            rs2.close();
                            ps2.close();
                        }
                    }
                } 
            }    
        } 
        
        else {
            JOptionPane.showMessageDialog(this, "No se encontró la placa ingresada.");
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al consultar: " + e.getMessage());
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NuevoTicket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnFlat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JRadioButton radioCatedratico;
    private javax.swing.JLabel txtCapacidad;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
        LocalDateTime ahora = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String fechaHoraFormateada = ahora.format(formato);     
        
}
