/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parkplus;

import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;
import javax.swing.text.Document;

/**
 *
 * @author pchin
 */
public class Reportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes.class.getName());

    public Reportes() {
        initComponents();
        dateDesde.setDate(new java.util.Date());
        dateHasta.setDate(new java.util.Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelReportesOpciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateDesde = new com.toedter.calendar.JDateChooser();
        dateHasta = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboEntraSal = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jScrollPane1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Reporte");

        jButton2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton2.setText("Actualizar");

        jButton3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton3.setText("Exportar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jButton2))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        panelReportesOpciones.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTES");

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setText("Selector de Fecha");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Desde");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Hasta");

        dateHasta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Reporte");

        comboTipo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cierre del Dia", "General por Fecha" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Tipo de Vehiculo");

        comboTipoVehiculo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        comboTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Moto", "Carro", "Catedratico" }));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Entrada / Salida");

        comboEntraSal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        comboEntraSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada y Salida", "Entrada", "Salida" }));

        javax.swing.GroupLayout panelReportesOpcionesLayout = new javax.swing.GroupLayout(panelReportesOpciones);
        panelReportesOpciones.setLayout(panelReportesOpcionesLayout);
        panelReportesOpcionesLayout.setHorizontalGroup(
            panelReportesOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReportesOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboTipoVehiculo, 0, 243, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelReportesOpcionesLayout.createSequentialGroup()
                        .addGroup(panelReportesOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboEntraSal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReportesOpcionesLayout.setVerticalGroup(
            panelReportesOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEntraSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelReportesOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReportesOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date desde = dateDesde.getDate();
        Date hasta = dateHasta.getDate();
        Connection con = ConexionSQL.conectar();
        if (desde == null || hasta == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar ambas fechas.");
            return;
        }

        if (desde.after(hasta)) {
            JOptionPane.showMessageDialog(null, "La fecha inicial no puede ser mayor que la final.");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String desdeString = sdf.format(desde);
        String hastaString = sdf.format(hasta);

        String tipoReporte = (String) comboTipo.getSelectedItem();
        String tipoVehiculo = (String) comboTipoVehiculo.getSelectedItem();
        String entradaSalida = (String) comboEntraSal.getSelectedItem();

        String key = tipoReporte + "|" + tipoVehiculo + "|" + entradaSalida;

        Map<String, Supplier<DefaultTableModel>> acciones = new HashMap<>();

        // --------------------- GENERAL POR FECHA ---------------------
        acciones.put("General por Fecha|Todos|Entrada y Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("General por Fecha|Todos|Entrada", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("General por Fecha|Todos|Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        
        acciones.put("General por Fecha|Carro|Entrada y Salida", () -> obtenerReporteGeneralCarroEntradaYSalida(desdeString, hastaString, con));
        acciones.put("General por Fecha|Carro|Entrada", () -> obtenerReporteGeneralCarroEntrada(desdeString, hastaString, con));
        acciones.put("General por Fecha|Carro|Salida", () -> obtenerReporteGeneralCarroSalida(desdeString, hastaString, con));

        acciones.put("General por Fecha|Moto|Entrada y Salida", () -> obtenerReporteGeneralMotoEntradaYSalida(desdeString, hastaString, con));
        acciones.put("General por Fecha|Moto|Entrada", () -> obtenerReporteGeneralMotoEntrada(desdeString, hastaString, con));
        acciones.put("General por Fecha|Moto|Salida", () -> obtenerReporteGeneralMotoSalida(desdeString, hastaString, con));

        acciones.put("General por Fecha|Catedratico|Entrada y Salida", () -> obtenerReporteGeneralCatedraticoEntradaYSalida(desdeString, hastaString, con));
        acciones.put("General por Fecha|Catedratico|Entrada", () -> obtenerReporteGeneralCatedraticoEntrada(desdeString, hastaString, con));
        acciones.put("General por Fecha|Catedratico|Salida", () -> obtenerReporteGeneralCatedraticoSalida(desdeString, hastaString, con));

        // --------------------- CIERRE DEL DÍA ---------------------
        acciones.put("Cierre del Dia|Carro|Entrada y Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("Cierre del Dia|Carro|Entrada", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("Cierre del Dia|Carro|Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));

        acciones.put("Cierre del Dia|Moto|Entrada y Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("Cierre del Dia|Moto|Entrada", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("Cierre del Dia|Moto|Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));

        acciones.put("Cierre del Dia|Catedratico|Entrada y Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("Cierre del Dia|Catedratico|Entrada", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));
        acciones.put("Cierre del Dia|Catedratico|Salida", () -> obtenerReporteCierreDelDia(desdeString, hastaString, con));

        // --------------------- EJECUCIÓN ---------------------
        Supplier<DefaultTableModel> accion = acciones.get(key);
        if (accion != null) {
            DefaultTableModel model = accion.get();
            tablaReportes.setModel(model);
            
        } else {
            JOptionPane.showMessageDialog(null, "No hay acción definida para esta combinación: " + key);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEntraSal;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboTipoVehiculo;
    private com.toedter.calendar.JDateChooser dateDesde;
    private com.toedter.calendar.JDateChooser dateHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelReportesOpciones;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables


    
    
public DefaultTableModel obtenerReporteGeneralCarroEntradaYSalida(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Entrada","Salida","Catedratico","Lugar","Tarifa","Total"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, hora_salida, esCatedratico, lugarOcupado, tarifa, total_pagar " +
                 "FROM historico " +
                 "WHERE tipoVehiculo = 'CARRO' AND esCatedratico = 0 AND hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getTimestamp("hora_salida"),
                rs.getInt("esCatedratico"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa"),
                rs.getDouble("total_pagar")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}
public DefaultTableModel obtenerReporteGeneralCarroEntrada(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Entrada","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE tipoVehiculo = 'CARRO' AND esCatedratico = 0 AND hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}
public DefaultTableModel obtenerReporteGeneralCarroSalida(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Salida","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_salida, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE tipoVehiculo = 'CARRO' AND esCatedratico = 0 AND hora_salida BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_salida"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}

public DefaultTableModel obtenerReporteGeneralMotoEntradaYSalida(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Entrada","Salida","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, hora_salida, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE tipoVehiculo = 'MOTO' AND esCatedratico = 0 " +
                 "AND hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getTimestamp("hora_salida"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}
public DefaultTableModel obtenerReporteGeneralMotoEntrada(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Entrada","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE tipoVehiculo = 'MOTO' AND esCatedratico = 0 AND hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}
public DefaultTableModel obtenerReporteGeneralMotoSalida(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Salida","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_salida, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE tipoVehiculo = 'MOTO' AND esCatedratico = 0 AND hora_salida BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_salida"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}

public DefaultTableModel obtenerReporteGeneralCatedraticoEntradaYSalida(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Entrada","Salida","Tipo Vehiculo","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, hora_salida, tipoVehiculo, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE esCatedratico = 1 AND hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getTimestamp("hora_salida"),
                rs.getString("tipoVehiculo"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}
public DefaultTableModel obtenerReporteGeneralCatedraticoEntrada(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Entrada","Tipo Vehiculo","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, tipoVehiculo, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE esCatedratico = 1 AND hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getString("tipoVehiculo"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}
public DefaultTableModel obtenerReporteGeneralCatedraticoSalida(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket","Placa","Salida","Tipo Vehiculo","Lugar","Tarifa"}, 0);

    String sql = "SELECT idTicket, placa, hora_salida, tipoVehiculo, lugarOcupado, tarifa " +
                 "FROM historico " +
                 "WHERE esCatedratico = 1 AND hora_salida BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_salida"),
                rs.getString("tipoVehiculo"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}

public DefaultTableModel obtenerReporteCierreDelDia(String desde, String hasta, Connection con) {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"IdTicket", "Placa", "Hora Entrada", "Hora Salida", "Tipo Vehiculo", "Lugar", "Tarifa", "Total"}, 0);

    String sql = "SELECT idTicket, placa, hora_entrada, hora_salida, tipoVehiculo, lugarOcupado, tarifa, total_pagar " +
                 "FROM historico " +
                 "WHERE hora_entrada BETWEEN ? AND ?";

    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setString(1, desde);
        ps.setString(2, hasta);

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("idTicket"),
                rs.getString("placa"),
                rs.getTimestamp("hora_entrada"),
                rs.getTimestamp("hora_salida"),
                rs.getString("tipoVehiculo"),
                rs.getString("lugarOcupado"),
                rs.getString("tarifa"),
                rs.getDouble("total_pagar")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return modelo;
}

}
